### PR TITLE
Activate Google Analytics

### PR DESCRIPTION
**Pull request by eternoendless**
Activate GA on the site

### CODE REVIEW

**Comment by PrestaEdit** [comment]
Mmmmmmh... With a cookie banner, I Hope ? 🤔

**Comment by eternoendless** [comment]
Good point @PrestaEdit 

We don't have a consent banner yet so I added an improvement to refuse consent by default: https://github.com/PrestaShop/ps-org-theme/pull/7

**Review by PrestaEdit — APPROVED** [review]

**Comment by okom3pom** [comment]
@eternoendless 

I wanted to know if it was complicated for you to use matomo?

We would stay in open source

**Comment by eternoendless** [comment]
It's an interesting option, but it comes with a cost (server infrastructure & maintenance to host it, or a monthly expense for the cloud version). I'd go with Analytics so that we can start tracking data ASAP, then investigate the options to migrate in the future.

**Review by matks — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Pull request merged**
