### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Improve README
| Fixed ticket |

### CODE REVIEW

**Comment by ttoine** [comment]
Not sure that I approve this new description. Because the work lost during the construction of the website has still a lot of value, and currently, it is missing...

**Comment by matks** [comment]
@ttoine I improved the README description, can you see the changes?

**Comment by ttoine** [comment]
yes, but maybe my answer was not clear enough. I don't enjoy what this repository is becoming. the original aim was to gather important resources and update them (usually, the outcome of months of work, to make it public). breaking everything to create a website is not really helpful for this use case.

it's either the website should have been in a dedicated folder (e.: /website/, like the other previous contents), or made in an other dedicated repository.

**Comment by ttoine** [comment]
yes.
what it means is that it might be reversed at one point.

**Review by kpodemski — APPROVED** [review]

**Pull request merged**
