### PR TITLE
Add prettyblocks

### PR DESCRIPTION
**Pull request by PrestaSafe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Add prettyblocks
| Fixed ticket | no fixes, documentation only

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by boherm** [comment]
Hi @PrestaSafe!
Thanks for your PR.
Regarding https://github.com/PrestaShop/open-source/pull/212, we certainly add `GitHub username` in the module presentation. 
If we merge 212 first, it's ok for you to edit your PR to add your GitHub username?

**Comment by PrestaSafe** [comment]
Hi @boherm it's ok for me, tell me if it's of for you with the new update ? 

Thanks.

**Review by nicosomb — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @PrestaSafe !

**Comment by PrestaSafe** [comment]
Thanks to you !

**Pull request merged**
