### PR TITLE
Update Issue managers / ST and SDT members for the project

### PR DESCRIPTION
**Pull request by sarahdib**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Update Issue managers / ST and SDT members for the project
| Fixed ticket | N/A

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]
This is wonderful news 🎉 welcome @MhiriFaten @sallemiines @paulnoelcholot @cfarhani06 @Progi1984

**Comment by matks** [comment]
Thank you @sarahdib

**Comment by PrestaEdit** [comment]
An issue manager is "de facto" a commiter ?

**Comment by kpodemski** [comment]
@PrestaEdit no, the Issue manager role is completely different 🤔 Committers don't handle Issue categorization, etc.

**Comment by PrestaEdit** [comment]
This, I know.

But, and as @Progi1984 say me, we could agree that with permissions accorded on GitHub, an issue manager have the committer rights ?

**Comment by kpodemski** [comment]
That may be true :) but the role is different, and no one expects the Issue manager to approve the code of Pull Requests, etc. 👍

**Comment by PrestaEdit** [comment]
Let me invite you on this : https://github.com/PrestaShop/productcomments/pull/141#pullrequestreview-1136154485

**Comment by kpodemski** [comment]
@PrestaEdit 

I understand. We cannot precisely control rights for specific user groups. If I'm not mistaken, you're writing about Paul-Noel's accepting the PR, it's completely fine. He didn't have to do it, but he could if the PR was approved after QA tests.

**Comment by Progi1984** [comment]
A SDT can approve some PR, as they are code owners of UI Tests,like developers are code owners of the core.
A ST can approve PR, as they test PRs and approve them before merging.

Issue Manager / ST are often the same people.

**Comment by PrestaEdit** [comment]
Thanks for theses informations, @Progi1984 !

It's a good thing too that peoples makes somes reviews, with or without the commiters roles, of course. I will never ask something others, for sure.
It's mainly to know/understand the project organization, as there is a lot of changes as this.

**Pull request merged**
