### PR TITLE
Remove Progi1984 from maintainers

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Remove me from maintainers

### CODE REVIEW

**Comment by jf-viguier** [comment]
noooooooooooooo, why ?

**Review by PululuK — APPROVED** [review]
Thanks for everything @Progi1984  ❤️

**Comment by kpodemski** [comment]
I'm a bit surprised as you being a maintainer would also help the company's projects and communicate better.

Anyway, thanks for your contributions Franck, @Progi1984 ❤️

**Review by okom3pom — APPROVED** [review]

**Comment by okom3pom** [comment]
Thank you for the time you took to help me, i aggree @kpodemski you could stay in this role but it's you choice 

See you at PS day for the beers.

**Review by matks — APPROVED** [review]
Thank you for everything 👍 you can be [proud](https://contributors.prestashop.com/) of your contribution to the project

**Review by PrestaEdit — APPROVED** [review]

**Comment by matks** [comment]
@Progi1984 I see you already removed yourself from the maintainer team so this PR can be merged as it only describes what is now the current situation

**Pull request merged**
