### PR TITLE
Remove PierreRambaud from maintainers

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Remove me from maintainers.

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]
@PierreRambaud I approve the PR content also I'm sad about the decision. Do you want to provide some context for people reading this? Or maybe you prefer people write to you in private if they wish to know the background behind?

**Comment by matks** [comment]
> Don't hesitate to correct me if I offend anyone or anything ^^

Looks fine to me 👍 😄 thank you for the feedback

**Review by jolelievre — APPROVED** [review]
🥲
❤️. on you @PierreRambaud

**Review by kpodemski — APPROVED** [review]
Thanks for everything Pierre ❤️

**Comment by Robin-Fischer-PS** [comment]
Thanks for everything @PierreRambaud , I hope you'll have fun in your next job :heart:

**Comment by Progi1984** [comment]
Thank you for all your work. You have been a mentor and a great colleague. Thanks

**Review by NeOMakinG — APPROVED** [review]
See you, mate, wish you the best 🤖

**Comment by boubkerbribri** [comment]
It was a pleasure working with you. Good luck on the next chapter :heart:

**Comment by matks** [comment]
Joining my peers to thank you for the hard work and saying it's been a pleasure.

You will remain at top of https://contributors.prestashop.com/ for a while I think

Would you be interested in becoming an [alumni](https://github.com/PrestaShop/open-source/issues/92)?

**Comment by PierreRambaud** [comment]
> Joining my peers to thank you for the hard work and saying it's been a pleasure.
> 
> You will remain at top of https://contributors.prestashop.com/ for a while I think
> 
> Would you be interested in becoming an [alumni](https://github.com/PrestaShop/open-source/issues/92)?

The only difference between alumni and a maintainer is: "You have the right, but no more duties", so I don't think it's a good thing for me as duties are really important for me :sweat_smile:

**Review by PrestaEdit — APPROVED** [review]
It's a sad decision for PrestaShop project, but it's yours !

Thanks for all, and good luck on your way !

**Review by Quetzacoalt91 — APPROVED** [review]
I see @PierreRambaud, I upvote

**Review by atomiix — APPROVED** [review]
Thanks for your good work and advices Pierre, wish you the best for your next adventure ❤️
(At least, table soccer games will be easier to win now 😄)

**Comment by Progi1984** [comment]
Thanks @PierreRambaud. 🥰

**Comment by jf-viguier** [comment]
Thanks @PierreRambaud for your amazing work and enjoy your next move.

**Review by PululuK — COMMENTED** [review]
**#RIP** 🙏

**Comment by khouloudbelguith** [comment]
@PierreRambaud Good luck on the next chapter :heart:

**Comment by HanaRebaiQA** [comment]
All the best @PierreRambaud for your personal and professional side :heart:

**Comment by okom3pom** [comment]
@PierreRambaud PierreRambaud  

thank you for your reviews and the moments shared!

**Comment by eternoendless** [comment]
I think I speak for everyone when I say how sorry we are to see you go @PierreRambaud. Thank you for everything you have done for the project, it's been a privilege working with you. I wish you all the best in your future endeavors.

**Comment by le-melon** [comment]
So it was not a robot?

**Pull request merged**
