### PR TITLE
Fix double slash for devdoclink

### PR DESCRIPTION
**Pull request by okom3pom**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description  | Fix double slash for devdoc link
| Fixed ticket | NA

### CODE REVIEW

**Review by PrestaEdit — APPROVED** [review]

**Comment by kpodemski** [comment]
Hi @okom3pom 

It seems that this PR is no longer relevant. Could you confirm?

**Comment by okom3pom** [comment]
Hello @kpodemski,

The PR need to be update without / at the end of `devdocs: "https://devdocs.prestashop-project.org/"` 

I will rebase my PR today

**Comment by okom3pom** [comment]
done 👍

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @okom3pom

**Pull request merged**
