### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by SimonGrn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix typo
| Type?         | improvement
| BC breaks?    |  no
| Deprecations? |  no
| How to test?  | ¯\\\_(ツ)_/¯

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
@SimonGrn Your "How to test" is not very helpful 😆

**Comment by SimonGrn** [comment]
> @SimonGrn Your "How to test" is not very helpful

I'm sorry ¯\\\_(ツ)_/¯

**Comment by matks** [comment]
> > @SimonGrn Your "How to test" is not very helpful
> 
> I'm sorry ¯\_(ツ)_/¯

You don't look like you're sorry

**Comment by matks** [comment]
Also the PR title is not really top class, see https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/pull-requests/#writing-a-good-title

**Pull request merged**
